name: CI

on:
  push:
    branches: [master]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [stable, unstable, development-target]
    container:
      image: ghcr.io/elementary/docker:${{ matrix.version }}

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        apt update
        apt install -y meson libgranite-dev libswitchboard-2.0-dev libxml2-dev libgnomekbd-dev libhandy-1-dev libibus-1.0-dev libxklavier-dev valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build install

  lint:

    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: io.elementary.vala-lint -d .
